### ISSUE TITLE
Performance is unacceptable

### ISSUE THREAD

**Issue by maenu** [haidaros/NullFinder#4]
Currently, performance is way to slow: 2h for 100mb or 109s for 3mb.
Analyse and find ways to improve.

**Comment by maenu** [comment]
When writing to a file: 1s for 3mb

**Comment by maenu** [comment]
When removing Java 8 streams from JavaSourceProcessor: 92s for 3mb

**Comment by maenu** [comment]
When removing all Java 8 Streams: 92s for 3mb

**Comment by haidaros** [comment]
Ok then. Removing streams seems to help a little bit. For now, I suggest to make the tool configurable so we can easily choose either to write to a file or to save to the database. We can investigate later the problem.

**Comment by maenu** [comment]
When not saving reasons: 42s for 3mb

**Comment by maenu** [comment]
Back to 13s for 3mb.
Caching of nodes seemed to be the issue.
